import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mhays' at '7/1/16 8:49 AM' with Gradle 2.13
 *
 * @author mhays, @date 7/1/16 8:49 AM
 */
public class LibraryTest {
    /*@Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
